tours = {
    "3MaasaiMara": "3-days-masai-mara-camping-joining-safaris",
    "4MaraNakuru": "4-days-masai-mara-nakuru-camping-joining-safari",
    "MaraSafari": "3-days-masai-mara-safari",
    "MNaks": "4-days-mara-nakuru-budget-safari",
    "MaraPrivate": "3-days-masai-mara-private-safari",
    "NakNaivasha": "5-days-budget-private-safari-to-maasai-mara-lake-nakuru-and-lake-naivasha-hells-gate",
    "AmboseliPrivate": "3-days-amboseli-private-safari",
    "6MNakAmb": "6-days-masai-mara-lake-nakuru-amboseli-safari",
    "Airport": "airport-transfers",
    "Kibera": "kibera-slums-tour",
    "LNakuru": "1-day-lake-nakuru-national-parkairport-transfers",
    "KTanzania": "7-dayskenya-tanzania-safaris-combined",
    "9KenyaTz": "9-days-combined-kenya-tanzania-safari-adventure",
    "12KenTz": "12-days-combined-kenya-tanzania-nairobi-l-nakuru-masai-mara-serengeti-ngorongoro-l-manyara-tarangire-arusha-safari",
    "5MtKen": "mt-kenya-climb-chogoria-route-naro-moru",
    "6MKenPeak": "mt-kenya-climbsirimon-naro-moru-with-peak-circuit-route",
    "5MtKen": "mt-kenya-climb-chogoria-route-naro-moru",
}