tours = {
    "HellsGate":"hellgate.html",
    "KereitaForest":"kereita.html",
    "Mara":"mara.html",
    "LMagadi":"lakemagadi.html",
    "LNakuru":"lakenakuru.html",
    "MtLongonot":"longonot.html",
    "NRBNational":"nairobinational.html",
    "Beach":"5beach.html",
    "Amboseli":"10dayamboseli.html",
    "8DayMara":"8daymara.html",
    "Samburu":"3daysamburu.html",
    "Bali":"6daybali.html",
    "Maldives":"6daymaldives.html",
    "Dubai":"5daydubai.html",
    "Seychelles":"5dayseychelles.html",
    "CapeTown":"5daycapetown.html",
    "EgyptIsrael":"10daysegyptisrael.html"
}